-- =============================================================================
-- Roles core table (RBAC) — Option A: BIGINT PK + public_id UUID
-- Depende de: V10 (extensiones + user_status) y V11 (app_user)
-- =============================================================================

-- Tabla de roles
CREATE TABLE IF NOT EXISTS role (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    code             TEXT NOT NULL UNIQUE,
    display_key      TEXT NOT NULL,
    description_key  TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by       BIGINT,
    deleted_at       TIMESTAMPTZ,
    deleted_by       BIGINT,
    version          INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT chk_role_code_upper CHECK (code = UPPER(code))
);

CREATE INDEX IF NOT EXISTS idx_role_display_key ON role(display_key);

ALTER TABLE role
    ADD CONSTRAINT fk_role_created_by
        FOREIGN KEY (created_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_role_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_role_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;