CREATE TABLE IF NOT EXISTS permission (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    code             TEXT NOT NULL UNIQUE,
    display_key      TEXT NOT NULL,
    description_key  TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by       BIGINT,
    deleted_at       TIMESTAMPTZ,
    deleted_by       BIGINT,
    version          INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT chk_permission_code_upper CHECK (code = UPPER(code))
);

CREATE INDEX IF NOT EXISTS idx_permission_display_key ON permission(display_key);

ALTER TABLE permission
    ADD CONSTRAINT fk_permission_created_by
        FOREIGN KEY (created_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_permission_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_permission_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;


