CREATE TABLE IF NOT EXISTS app_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    username         CITEXT NOT NULL UNIQUE,
    email            CITEXT UNIQUE,
    password_hash    TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'ACTIVE',
    email_verified   BOOLEAN NOT NULL DEFAULT FALSE,
    is_service       BOOLEAN NOT NULL DEFAULT FALSE,
    can_login        BOOLEAN NOT NULL DEFAULT TRUE,
    is_protected     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by       BIGINT,
    deleted_at       TIMESTAMPTZ,
    deleted_by       BIGINT,
    version          INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_app_user_status
        FOREIGN KEY (status) REFERENCES user_status(code)
            ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_app_user_status ON app_user(status);
CREATE INDEX IF NOT EXISTS idx_app_user_email_verified ON app_user(email_verified);
CREATE INDEX IF NOT EXISTS idx_app_user_is_service ON app_user(is_service);

ALTER TABLE app_user
    ADD CONSTRAINT fk_app_user_created_by
        FOREIGN KEY (created_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_app_user_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_app_user_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES app_user(id)
            ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;